### ISSUE TITLE
Integrate AMS 0.9 with new Rails 5 project

### ISSUE THREAD

**Issue by oyeanuj** [oyeanuj/Rails5-AMS0.9#1]
Source issue: https://github.com/rails-api/active_model_serializers/issues/1923
Latest update: https://github.com/rails-api/active_model_serializers/issues/1923#issuecomment-275880797

Success Criteria: 
1. Get Rails 5 and AMS 9 working together, so that one can use the generators to create a new resource, serializers and have it all working for a basic example.
2. Make necessary PR to the AMS repo to get this to work.

Feel free to create a new Rails 5 Project with ActiveModelSerializer 0.9 if needed.

**Comment by oyeanuj** [comment]
codemill$

**Comment by oyeanuj** [comment]
codemill$50

**Comment by oyeanuj** [comment]
codemill$50

**Comment by oyeanuj** [comment]
codemill$75

**Comment by oyeanuj** [comment]
Fixed by https://github.com/rails-api/active_model_serializers/pull/2167

**Comment by hiradyazdan** [comment]
@oyeanuj has this been merged, it looks like this has been left untouched for a long time?
